name: Translation
description: Request a translation
title: ":globe_with_meridians: "
body:
  - type: markdown
    attributes:
      value: |
        We appreciate you taking the time to fill out this translation request!
  - type: input
    id: word
    attributes:
      label: What word do you want to translate (or see translated)?
    validations:
      required: true
  - type: input
    id: language
    attributes:
      label: What langauge would you like to this definition translated to?
    validations:
      required: true
  - type: checkboxes
    id: assign-to-me
    attributes:
      label: Would you like to lead translating this word?
      description: By checking this, you'll be assigned this issue and we'll work with you to get the definition added should it be accepted!
      options:
        - label: Yeah, assign it to me!
  - type: checkboxes
    id: have-reviewer
    attributes:
      label: Do you have any fluent colleagues who could review your translations?
      description: Translations will always be shared with our community to review, but we recognise that many languages are not yet widely represented. We always want to ensure all entries are peer-reviewed by as many folks as possible.
      options:
        - label: Yeah, I'll have someone review it!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/selfdefined/web-app/blob/prod/CODE-OF-CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
